program: cnn_v3.py
method: random
metric:
    name: accuracy_val
    metric: accuracy
    goal: maximize

# Parameters which are mentioned in the paper, are kept constant
# Parameters regarding architecture are excluded and defined in the program
parameters:
    lr:
        distribution: uniform
        min: 0.0001
        max: 0.01

    batch_size:
        values: [16, 32, 64, 128]

    num_epochs:
        values: [1, 2, 3, 4, 5]

    optimizer:
        values: ["adam", "sgd"]

    num_symbols:
        values: 128

    activation:
        values: "relu"

    pooling_layer:
        values: "avgpool"

    kernel_size:
        values: 4
